### ISSUE TITLE
highlight-1-responsive layout does not highlight active speaker

### ISSUE THREAD

**Issue by brandonfancher** [signalwire/browser-videoconf-full-react#11]
When we specify `layout: "highlight-1-responsive"` in the `RoomConfig` when creating a room by posting to the "rooms" endpoint, the video call starts with the `highlight-1-responsive` layout, but it does not actively move the active speaker to the larger square in the top-left position as it should.

However, if we _switch to_ that layout using the JS `setLayout({ name: "highlight-1-responsive" })`, it DOES respond properly to the active speaker.

**Comment by brandonfancher** [comment]
@danieleds @kamroot This is the issue I mentioned on the call the other day with you guys.

**Comment by danieleds** [comment]
@brandonfancher thanks! Investigating

**Comment by danieleds** [comment]
@brandonfancher a fix has been released and is currently live. Feel free to reopen should the issue occur again :)
