### ISSUE TITLE
How to have the Video in portrait mode 

### ISSUE THREAD

**Issue by CS730** [signalwire/browser-videoconf-full-react#2]
I tried searching over the docs a bit but didn't get much about this. I want to make this application work on mobile view, though it still works the landscape mode makes the view very small. 
Is there any way so that we can make the entire Video Stream be in portrait mode !!
Also even if we can increase the height of the window a bit that would make it work too.

**Comment by danieleds** [comment]
Hi! Is this a bit more similar to what you're looking for? https://9eqvl.csb.app/ 

source code: https://codesandbox.io/s/zoom-clone-livewire-extras-forked-9eqvl
