### ISSUE TITLE
Duplicated video when joining an existing room

### ISSUE THREAD

**Issue by sparkplug0025** [signalwire/browser-videoconf-full-react#3]
I'm on the master branch and I was able to produce the following bug when joining a room with multiple another two users:
![image](https://user-images.githubusercontent.com/79721020/160743262-2e62c9f8-7eeb-4989-847c-5aaa9e852e3b.png)

It seems like a duplication of my video is displayed, I delve a little bit in the signalwire js libs but I was not able to find out why it's happening. 

I'm on a Windows 11, using three browsers to test: Chrome, Edge and Brave. I keep two of the browsers with muted videos and one of them (the one with the bug) with the video camera enabled. I've seen this bug happening in all of the three browsers already while joining/rejoining the ongoing meeting.

Is it the proper channel to ask for help? Should I open a ticket in SignalWire customer support as well referencing this issue?

Thank you in advance.

**Comment by danieleds** [comment]
Hi @sparkplug0025,

thanks for reporting. It seems that the version of the SDK used on the master branch needs to be updated: we are going to push a fix very soon.

**Comment by sparkplug0025** [comment]
Same issue...
<img width="934" alt="image" src="https://user-images.githubusercontent.com/79721020/160963088-a33bceed-38aa-4dd4-9f8e-3758248ffab0.png">

This time happened with edge, as soon as I joined the room (it was not a re-joining situation)

**Comment by sparkplug0025** [comment]
Just as a FYI, I did pulled the vue repo and I was able to reproduce the same issue:
<img width="946" alt="image" src="https://user-images.githubusercontent.com/79721020/160968200-41a4ef8b-98f8-42ba-8cc2-65fe738da63e.png">

I was wondering if it was maybe some bug in the react implementation but it seems to be something in the sdk itself...

**Comment by danieleds** [comment]
Thanks! We are investigating and will get back to you

**Comment by danieleds** [comment]
@sparkplug0025 we have patched the SDK. You can pull the new changes from this repo, and reinstall the dependencies from the `video/` directory. This should fix the issue.

**Comment by sparkplug0025** [comment]
It seems like it's fixed! I tried many times and I could not reproduce this one! 🎉 

Thank you so much @danieleds ! I will close for now, if we observe it again I will reopen!
