### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by getarun** [signalwire/browser-videoconf-full-react#4]
**What happens**: Cannot start back/frontend.

**How to reproduce**: 
1. Clone repositories master branch and cd into its root. 
2. run yarn install which fails with "ERROR: [Errno 2] No such file or directory: 'install' "

**Expected behavior**: yarn should pull dependencies and install them.

**Comment by danieleds** [comment]
Hi @getarun ,
which OS are you on?

**Comment by getarun** [comment]
Ubuntu 20.04
kernel: 5.13.0-37-generic

**Comment by danieleds** [comment]
I believe you have the wrong "yarn" installed in your system.

Could you try following the instructions here? https://stackoverflow.com/a/47680872

**Comment by getarun** [comment]
yes, thank you :)
