### ISSUE TITLE
Participant Statuses out of Sync

### ISSUE THREAD

**Issue by sparkplug0025** [signalwire/browser-videoconf-full-react#6]
I noticed that sometimes when I joined with a third member in the room the Muting statuses get out of sync: 

This was my flow (and I hope you can reproduce as well):
1. joined with chrome and mute both camera and mic
2. joined with brave and mute both camera and mic
3. joined with edge and mute only mic, but all of sudden here are the statuses that I see:

Edge has proper statuses:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/79721020/160963614-70f2b0d2-cf26-4d48-b9ef-bd1ffafc1076.png">

Brave displays itself as unmuted mic:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/79721020/160963370-1e1a88a0-5a08-4261-93f4-2abe2203a4a8.png">
(although here I still know brave is muted because the footer menu has a red mic and because I can't hear any echo)

Chrome displays itself as unmuted mic and video, and also displays Brave as unmuted mic and camera:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/79721020/160963956-6cf334a8-ac21-40c4-bfb3-67c09ec75794.png">

(likewise here I know Chrome has no video and mic because I can see it in the bottom menu, and also in the video conference)
<img width="731" alt="image" src="https://user-images.githubusercontent.com/79721020/160964157-2d71ad4a-42f4-4439-8ab0-d81e03d5e81f.png">

Although these were reproduced locally, we already experienced these out of sync statuses among real participants in internal tests calls that we've been doing.

**Comment by danieleds** [comment]
@sparkplug0025, thanks for reporting the issue. We have released a fix in v3.10.2 of the SDK: you may want to upgrade to that one. Feel free to close the issue if you can confirm that the problem is solved.

We updated this repo to use v3.10.2, and we also applied minor fixes to the UI, so you may want to pull the new changes.

**Comment by sparkplug0025** [comment]
It seems fixed too! This is great! 🎉 If I notice this bug again I will reopen it!

Thanks for the quick response to all the issues that I'm reporting here! 🙏
